---
- name: Get ARP information
  hosts: gns3_hosts
  gather_facts: false


  tasks:
    - name: show arp
      raw: "show arp"

      register: print_output

    -  debug: var=print_output.stdout_lines
